import type { Metadata } from "next";
import {
  barlowBold,
  barlowBlack,
  barlowRegular,
  barlowLight,
  barlowMedium
} from '@/src/utils/fonts';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("cambia");
  
  return (
    <html lang="en">
      <body
        className={`
          ${barlowBold.variable}
          ${barlowMedium.variable}
          ${barlowRegular.variable}
          ${barlowLight.variable}
          ${barlowBlack.variable}
          antialiased bg-gray-100 overflow-y-hidden`
        }
      >
        {children}
      </body>
    </html>
  );
}
